#mysql数据库表结构

DROP TABLE IF EXISTS `MANAGER`;
CREATE TABLE `MANAGER` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '账号',
  `PASSWORD` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
  `EMAIL` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `MOBILE` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '手机',
  `CREATE_TIME` CHAR(19) NOT NULL DEFAULT '' COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统管理员表';

DROP TABLE IF EXISTS `FOLDER`;
CREATE TABLE `FOLDER` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '名称',
  `PARENT_ID` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '父ID',
  `CREATE_TIME` CHAR(19) NOT NULL DEFAULT '' COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='分类表';

DROP TABLE IF EXISTS `RESOURCE`;
CREATE TABLE `RESOURCE` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `FOLDER_ID` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '分类ID',
  `CODE` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '编号',
  `NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '名称',
  `CREATE_TIME` CHAR(19) NOT NULL DEFAULT '' COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资源表';


INSERT INTO MANAGER (NAME,PASSWORD,EMAIL,MOBILE,CREATE_TIME) VALUES ('admin','$2a$10$oe/ovruYdv0EmNsKWLJwfu6Na51whOBRJOAJxBO.yt/C6DxQhdDNK','10000@qq.com','13720044306','2018-09-11 12:00:00');
#可选的操作：插入用户：admin  密码：admin123
